# Generated by Django 4.2.7 on 2024-03-15 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionUtilisateurs', '0001_initial'),
        ('gestionStocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Photo')),
                ('ordonnanceClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUtilisateurs.client')),
                ('ordonnancePharmacien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUtilisateurs.pharmacien')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixTotal', models.IntegerField()),
                ('dateCommande', models.DateTimeField()),
                ('etatDeCommande', models.BooleanField()),
                ('etatDeLivraison', models.BooleanField()),
                ('commandeCaissier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUtilisateurs.caissier')),
                ('commandeLivreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUtilisateurs.livreur')),
                ('commandeMedicament', models.ManyToManyField(to='gestionStocks.medicament')),
                ('commandeOrdonnance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionVentes.ordonnance')),
                ('commandePharmacien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUtilisateurs.pharmacien')),
            ],
        ),
    ]
