# Generated by Django 4.2.7 on 2024-08-01 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionUtilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('virtuelle', 'Virtuelle'), ('presentiel', 'Presentiel')], max_length=50)),
                ('donnees', models.JSONField()),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('etatDeValidation', models.BooleanField(default=False)),
                ('pharmacien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUtilisateurs.pharmacien')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ordonnance_images/', verbose_name='Photo')),
                ('ordonnance_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUtilisateurs.client')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_de_livraison', models.BooleanField(default=False)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUtilisateurs.livreur')),
                ('ordonnance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionVentes.ordonnance')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeVirtuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geolocalisation', models.CharField(blank=True, max_length=255, null=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('consentement', models.BooleanField(default=False)),
                ('mode_paiement', models.CharField(choices=[('tmoney', 'Tmoney'), ('flooz', 'Flooz')], max_length=50)),
                ('etat_validation', models.BooleanField(default=False)),
                ('motif', models.CharField(default='Ordonnance correcte', max_length=255)),
                ('ordonnance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionVentes.ordonnance')),
            ],
        ),
        migrations.CreateModel(
            name='CommandePresentielle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixTotal', models.IntegerField()),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('caissier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUtilisateurs.caissier')),
                ('selection_medicaments', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionVentes.selectionmedicament')),
            ],
        ),
    ]
