# Generated by Django 5.0.7 on 2024-08-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandevirtuelle',
            name='frais_livraison',
            field=models.IntegerField(default=0),
        ),
    ]
