# Generated by Django 5.0.7 on 2024-07-30 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUtilisateurs', '0001_initial'),
        ('gestionVentes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandevirtuelle',
            old_name='etatDeCommande',
            new_name='etat_commande',
        ),
        migrations.RenameField(
            model_name='commandevirtuelle',
            old_name='commandePharmacien',
            new_name='pharmacien',
        ),
        migrations.RenameField(
            model_name='commandevirtuelle',
            old_name='prixTotal',
            new_name='prix_total',
        ),
        migrations.RenameField(
            model_name='ordonnance',
            old_name='ordonnanceClient',
            new_name='ordonnance_client',
        ),
        migrations.RemoveField(
            model_name='commandevirtuelle',
            name='commandeCaissier',
        ),
        migrations.RemoveField(
            model_name='commandevirtuelle',
            name='commandeLivreur',
        ),
        migrations.RemoveField(
            model_name='commandevirtuelle',
            name='commandeMedicament',
        ),
        migrations.RemoveField(
            model_name='commandevirtuelle',
            name='commandeOrdonnance',
        ),
        migrations.RemoveField(
            model_name='commandevirtuelle',
            name='dateCommande',
        ),
        migrations.RemoveField(
            model_name='commandevirtuelle',
            name='etatDeLivraison',
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='ordonnancePharmacien',
        ),
        migrations.CreateModel(
            name='FormulaireCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geolocalisation', models.CharField(blank=True, max_length=255, null=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('consentement', models.BooleanField(default=False)),
                ('mode_paiement', models.CharField(choices=[('tmoney', 'Tmoney'), ('flooz', 'Flooz')], max_length=50)),
                ('ordonnance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionVentes.ordonnance')),
            ],
        ),
        migrations.AddField(
            model_name='commandevirtuelle',
            name='formulaire_commande',
            field=models.OneToOneField(default=9, on_delete=django.db.models.deletion.CASCADE, to='gestionVentes.formulairecommande'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_de_livraison', models.BooleanField(default=False)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUtilisateurs.livreur')),
                ('ordonnance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionVentes.ordonnance')),
            ],
        ),
        migrations.CreateModel(
            name='PayementCommandeVirtuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('etat_de_livraison', models.BooleanField(default=False)),
                ('caissier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUtilisateurs.caissier')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionVentes.commandevirtuelle')),
            ],
        ),
    ]
