# Generated by Django 4.2.7 on 2024-08-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandevirtuelle',
            name='etat_payement',
            field=models.BooleanField(default=False),
        ),
    ]
