# Generated by Django 4.2.7 on 2024-08-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectionmedicament',
            name='prixTotal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
