# Generated by Django 4.2.7 on 2024-08-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectionmedicament',
            name='etatOrdonnance',
            field=models.BooleanField(default=False),
        ),
    ]
