# Generated by Django 4.2.7 on 2024-07-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='image',
            field=models.ImageField(upload_to='ordonnance_images/', verbose_name='Photo'),
        ),
    ]
