# Generated by Django 4.2.7 on 2024-07-27 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUtilisateurs', '0007_remove_caissier_is_active_remove_caissier_is_staff_and_more'),
        ('gestionStocks', '0003_alter_medicament_medicamentcategorie'),
        ('gestionVentes', '0002_alter_ordonnance_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandePresentielle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('caissier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUtilisateurs.caissier')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeVirtuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixTotal', models.IntegerField()),
                ('dateCommande', models.DateTimeField()),
                ('etatDeCommande', models.BooleanField(default=False)),
                ('etatDeLivraison', models.BooleanField(default=False)),
                ('commandeCaissier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUtilisateurs.caissier')),
                ('commandeLivreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUtilisateurs.livreur')),
                ('commandeMedicament', models.ManyToManyField(to='gestionStocks.medicament')),
                ('commandeOrdonnance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionVentes.ordonnance')),
                ('commandePharmacien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUtilisateurs.pharmacien')),
            ],
        ),
        migrations.CreateModel(
            name='SelectionMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnees', models.JSONField()),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('etatDeValidation', models.BooleanField(default=False)),
                ('pharmacien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUtilisateurs.pharmacien')),
            ],
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.AddField(
            model_name='commandepresentielle',
            name='selection_medicaments',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionVentes.selectionmedicament'),
        ),
    ]
