# Generated by Django 4.2.7 on 2024-08-05 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentes', '0002_commandevirtuelle_etat_payement'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectionmedicament',
            name='ordonnance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='gestionVentes.ordonnance'),
        ),
    ]
