# Generated by Django 4.2.7 on 2024-07-30 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUtilisateurs', '0007_remove_caissier_is_active_remove_caissier_is_staff_and_more'),
        ('gestionVentes', '0002_alter_ordonnance_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandePresentielle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixTotal', models.IntegerField()),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('caissier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUtilisateurs.caissier')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeVirtuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_total', models.IntegerField()),
                ('etat_commande', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FormulaireCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geolocalisation', models.CharField(blank=True, max_length=255, null=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('consentement', models.BooleanField(default=False)),
                ('mode_paiement', models.CharField(choices=[('tmoney', 'Tmoney'), ('flooz', 'Flooz')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_de_livraison', models.BooleanField(default=False)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUtilisateurs.livreur')),
            ],
        ),
        migrations.CreateModel(
            name='PayementCommandeVirtuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('etat_de_livraison', models.BooleanField(default=False)),
                ('caissier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUtilisateurs.caissier')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionVentes.commandevirtuelle')),
            ],
        ),
        migrations.CreateModel(
            name='SelectionMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnees', models.JSONField()),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('etatDeValidation', models.BooleanField(default=False)),
                ('pharmacien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUtilisateurs.pharmacien')),
            ],
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='ordonnanceClient',
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='ordonnancePharmacien',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='ordonnance_client',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='gestionUtilisateurs.client'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.AddField(
            model_name='livraison',
            name='ordonnance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionVentes.ordonnance'),
        ),
        migrations.AddField(
            model_name='formulairecommande',
            name='ordonnance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionVentes.ordonnance'),
        ),
        migrations.AddField(
            model_name='commandevirtuelle',
            name='formulaire_commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionVentes.formulairecommande'),
        ),
        migrations.AddField(
            model_name='commandevirtuelle',
            name='pharmacien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUtilisateurs.pharmacien'),
        ),
        migrations.AddField(
            model_name='commandepresentielle',
            name='selection_medicaments',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionVentes.selectionmedicament'),
        ),
    ]
