# Generated by Django 4.2.7 on 2024-08-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentes', '0002_selectionmedicament_prixtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandevirtuelle',
            name='frais_livraison',
            field=models.IntegerField(default=0),
        ),
    ]
