# Generated by Django 4.2.7 on 2024-08-05 23:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentes', '0003_selectionmedicament_ordonnance'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='date_validation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
