# Generated by Django 4.2.7 on 2024-07-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentes', '0003_commandepresentielle_commandevirtuelle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandepresentielle',
            name='prixTotal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
