# Generated by Django 5.0.7 on 2024-07-28 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionUtilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCat', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomMedicament', models.CharField(max_length=150)),
                ('libelle', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('prixUnitaire', models.IntegerField()),
                ('dateExpiration', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicament_images/')),
                ('medicamentCategorie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='medicaments', to='gestionStocks.categorie')),
                ('medicamentPreparateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUtilisateurs.preparateurenpharmacie')),
            ],
        ),
    ]
