# Generated by Django 4.2.7 on 2024-08-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
