# Generated by Django 4.2.7 on 2024-06-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicament_images/'),
        ),
    ]
