# Generated by Django 4.2.7 on 2024-07-06 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStocks', '0002_medicament_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='medicamentCategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='medicaments', to='gestionStocks.categorie'),
        ),
    ]
