# Generated by Django 4.2.7 on 2024-08-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caissier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUtilisateur', models.CharField(max_length=100)),
                ('prenomUtilisateur', models.CharField(max_length=150)),
                ('numeroUtilisateur', models.IntegerField()),
                ('adresseUtilisateur', models.CharField(max_length=255)),
                ('emailUtilisateur', models.EmailField(max_length=254, unique=True)),
                ('motDePasse', models.CharField(max_length=100)),
                ('role', models.CharField(default='utilisateur', max_length=150)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUtilisateur', models.CharField(max_length=100)),
                ('prenomUtilisateur', models.CharField(max_length=150)),
                ('numeroUtilisateur', models.IntegerField()),
                ('adresseUtilisateur', models.CharField(max_length=255)),
                ('emailUtilisateur', models.EmailField(max_length=254, unique=True)),
                ('motDePasse', models.CharField(max_length=100)),
                ('role', models.CharField(default='utilisateur', max_length=150)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GestionnairePharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUtilisateur', models.CharField(max_length=100)),
                ('prenomUtilisateur', models.CharField(max_length=150)),
                ('numeroUtilisateur', models.IntegerField()),
                ('adresseUtilisateur', models.CharField(max_length=255)),
                ('emailUtilisateur', models.EmailField(max_length=254, unique=True)),
                ('motDePasse', models.CharField(max_length=100)),
                ('role', models.CharField(default='utilisateur', max_length=150)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUtilisateur', models.CharField(max_length=100)),
                ('prenomUtilisateur', models.CharField(max_length=150)),
                ('numeroUtilisateur', models.IntegerField()),
                ('adresseUtilisateur', models.CharField(max_length=255)),
                ('emailUtilisateur', models.EmailField(max_length=254, unique=True)),
                ('motDePasse', models.CharField(max_length=100)),
                ('role', models.CharField(default='utilisateur', max_length=150)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pharmacien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUtilisateur', models.CharField(max_length=100)),
                ('prenomUtilisateur', models.CharField(max_length=150)),
                ('numeroUtilisateur', models.IntegerField()),
                ('adresseUtilisateur', models.CharField(max_length=255)),
                ('emailUtilisateur', models.EmailField(max_length=254, unique=True)),
                ('motDePasse', models.CharField(max_length=100)),
                ('role', models.CharField(default='utilisateur', max_length=150)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreparateurEnPharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUtilisateur', models.CharField(max_length=100)),
                ('prenomUtilisateur', models.CharField(max_length=150)),
                ('numeroUtilisateur', models.IntegerField()),
                ('adresseUtilisateur', models.CharField(max_length=255)),
                ('emailUtilisateur', models.EmailField(max_length=254, unique=True)),
                ('motDePasse', models.CharField(max_length=100)),
                ('role', models.CharField(default='utilisateur', max_length=150)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
