# Generated by Django 4.2.7 on 2024-06-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUtilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caissier',
            name='role',
            field=models.CharField(default='utilisateur', max_length=150),
        ),
        migrations.AddField(
            model_name='client',
            name='role',
            field=models.CharField(default='utilisateur', max_length=150),
        ),
        migrations.AddField(
            model_name='gestionnairepharmacie',
            name='role',
            field=models.CharField(default='utilisateur', max_length=150),
        ),
        migrations.AddField(
            model_name='livreur',
            name='role',
            field=models.CharField(default='utilisateur', max_length=150),
        ),
        migrations.AddField(
            model_name='pharmacien',
            name='role',
            field=models.CharField(default='utilisateur', max_length=150),
        ),
        migrations.AddField(
            model_name='preparateurenpharmacie',
            name='role',
            field=models.CharField(default='utilisateur', max_length=150),
        ),
    ]
