# Generated by Django 4.2.7 on 2024-07-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUtilisateurs', '0002_caissier_role_client_role_gestionnairepharmacie_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caissier',
            name='emailUtilisateur',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='emailUtilisateur',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='gestionnairepharmacie',
            name='emailUtilisateur',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='emailUtilisateur',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='pharmacien',
            name='emailUtilisateur',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='preparateurenpharmacie',
            name='emailUtilisateur',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
