# Generated by Django 4.2.7 on 2024-07-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUtilisateurs', '0003_alter_caissier_emailutilisateur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caissier',
            name='role',
        ),
        migrations.RemoveField(
            model_name='client',
            name='role',
        ),
        migrations.RemoveField(
            model_name='gestionnairepharmacie',
            name='role',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='role',
        ),
        migrations.RemoveField(
            model_name='pharmacien',
            name='role',
        ),
        migrations.RemoveField(
            model_name='preparateurenpharmacie',
            name='role',
        ),
        migrations.AddField(
            model_name='caissier',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestionnairepharmacie',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacien',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preparateurenpharmacie',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
