# Generated by Django 4.2.7 on 2024-07-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUtilisateurs', '0004_remove_caissier_role_remove_client_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caissier',
            name='role',
            field=models.CharField(default='utilisateur', max_length=150),
        ),
        migrations.AddField(
            model_name='client',
            name='role',
            field=models.CharField(default='utilisateur', max_length=150),
        ),
        migrations.AddField(
            model_name='gestionnairepharmacie',
            name='role',
            field=models.CharField(default='utilisateur', max_length=150),
        ),
        migrations.AddField(
            model_name='livreur',
            name='role',
            field=models.CharField(default='utilisateur', max_length=150),
        ),
        migrations.AddField(
            model_name='pharmacien',
            name='role',
            field=models.CharField(default='utilisateur', max_length=150),
        ),
        migrations.AddField(
            model_name='preparateurenpharmacie',
            name='role',
            field=models.CharField(default='utilisateur', max_length=150),
        ),
    ]
