# Generated by Django 4.2.7 on 2024-07-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUtilisateurs', '0005_caissier_role_client_role_gestionnairepharmacie_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caissier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caissier',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caissier',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caissier',
            name='password',
            field=models.CharField(default='motdepasse', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='motdepasse', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gestionnairepharmacie',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gestionnairepharmacie',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gestionnairepharmacie',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gestionnairepharmacie',
            name='password',
            field=models.CharField(default='motdepasse', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livreur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livreur',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livreur',
            name='password',
            field=models.CharField(default='motdepasse', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacien',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pharmacien',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacien',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacien',
            name='password',
            field=models.CharField(default='motdepasse', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preparateurenpharmacie',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preparateurenpharmacie',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preparateurenpharmacie',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preparateurenpharmacie',
            name='password',
            field=models.CharField(default='motdepasse', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caissier',
            name='motDePasse',
            field=models.CharField(default='pbkdf2_sha256$600000$ZHrCdlaBAeMDX2NUvd9x3n$OCtKl0a+2Fak4iKLtTvInsLlDJNpuXkgRIuNZX2xs/g=', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='motDePasse',
            field=models.CharField(default='pbkdf2_sha256$600000$ZHrCdlaBAeMDX2NUvd9x3n$OCtKl0a+2Fak4iKLtTvInsLlDJNpuXkgRIuNZX2xs/g=', max_length=100),
        ),
        migrations.AlterField(
            model_name='gestionnairepharmacie',
            name='motDePasse',
            field=models.CharField(default='pbkdf2_sha256$600000$ZHrCdlaBAeMDX2NUvd9x3n$OCtKl0a+2Fak4iKLtTvInsLlDJNpuXkgRIuNZX2xs/g=', max_length=100),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='motDePasse',
            field=models.CharField(default='pbkdf2_sha256$600000$ZHrCdlaBAeMDX2NUvd9x3n$OCtKl0a+2Fak4iKLtTvInsLlDJNpuXkgRIuNZX2xs/g=', max_length=100),
        ),
        migrations.AlterField(
            model_name='pharmacien',
            name='motDePasse',
            field=models.CharField(default='pbkdf2_sha256$600000$ZHrCdlaBAeMDX2NUvd9x3n$OCtKl0a+2Fak4iKLtTvInsLlDJNpuXkgRIuNZX2xs/g=', max_length=100),
        ),
        migrations.AlterField(
            model_name='preparateurenpharmacie',
            name='motDePasse',
            field=models.CharField(default='pbkdf2_sha256$600000$ZHrCdlaBAeMDX2NUvd9x3n$OCtKl0a+2Fak4iKLtTvInsLlDJNpuXkgRIuNZX2xs/g=', max_length=100),
        ),
    ]
